apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: gzje2eji8-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/gzje2eji8-dotnet-basic-gitops